version: "3.8"

services:
  users-service:
    image: users-service:1.0
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://sic_db_user:sicproject@cluster0.mzx76ay.mongodb.net/?appName=Cluster0
    networks:
      - sic-project-net

  favorites-service:
    image: favorites-service:1.0
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb+srv://sic_db_user:sicproject@cluster0.mzx76ay.mongodb.net/?appName=Cluster0
    networks:
      - sic-project-net

  markets-service:
    image: markets-service:1.0
    ports:
      - "4000:4000"
    environment:
      - GRAPHQL_PORT=4000
      - MONGO_URL=mongodb+srv://sic_db_user:sicproject@cluster0.mzx76ay.mongodb.net/?appName=Cluster0
      - JWT_SECRET=aminhachavesecreta123
    networks:
      - sic-project-net

  notes-service:
    image: notes-service:1.0
    ports:
      - "3005:3005"
    environment:
      - MONGO_URL=mongodb+srv://sic_db_user:sicproject@cluster0.mzx76ay.mongodb.net/?appName=Cluster0
    networks:
      - sic-project-net

  notifications-service:
    image: notifications-service:1.0
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb+srv://sic_db_user:sicproject@cluster0.mzx76ay.mongodb.net/?appName=Cluster0
    networks:
      - sic-project-net

  ratings-service:
    image: ratings-service:1.0
    ports:
      - "3004:3004"
    environment:
      - MONGO_URL=mongodb+srv://sic_db_user:sicproject@cluster0.mzx76ay.mongodb.net/?appName=Cluster0
    networks:
      - sic-project-net

  api-gateway:
    image: api-gateway:1.0
    ports:
      - "80:80"
    networks:
      - sic-project-net

networks:
  sic-project-net:
    driver: bridge